### PR TITLE
Added an alternative Makefile-based build system for Unix-like OSes (which should also work in Windows)

### PR DESCRIPTION
**Pull request by dragontamer8740**
I don't like having to use an IDE, and Eclipse in particular is unstable on my system. So I made a simple Makefile and a manifest file (the manifest is usually generated by the IDE).

Please consider accepting it. Thanks for making this :)

I believe it would work on Windows with a "make" implementation, but I have not tested it there. I am 100% sure that it would work in MinGW/MSYS. Cygwin would be trickier but should also work relatively painlessly once you have a JDK built inside it.

### CODE REVIEW

**Comment by Chase-san** [comment]
Any chance you could make one of these to use Ant instead, it's basically Java's version of Make, but made for Java (in Java).

Make is pretty Legacy these days, and doesn't fit Java's requirements well. Ant is designed for java and can even generate the manifest file.

[Here is an example, an ant file I wrote for a different program.](https://github.com/Chase-san/Automation-Track-Editor/blob/master/build.ant)

**Comment by dragontamer8740** [comment]
I really have zero experience with ant, unfortunately.
I wrote a makefile because I understand make. I'm mostly a C programmer.

**Comment by dragontamer8740** [comment]
Alright, made an ant file. Shall I remove the Makefile?
(edit: I removed it.)

**Comment by Chase-san** [comment]
Let me know when you have tested it and it works.

**Comment by dragontamer8740** [comment]
> Let me know when you have tested it and it works.

I already did test it before pushing; it works.

**Pull request merged**
